
import React from 'react';
import ServiceDetail from '@/components/ServiceDetail';

const TaxExemption80IAC = () => {
  const serviceData = {
    title: "80 IAC Tax Exemption Registration",
    description: "Comprehensive assistance for eligible startups to obtain tax exemption under Section 80 IAC of the Income Tax Act, offering 100% deduction on profits for three consecutive years.",
    price: 12999,
    category: "Registrations",
    serviceType: "80 IAC Tax Exemption",
    features: [
      "100% Profit Tax Exemption for 3 Consecutive Years",
      "Eligibility Selection from First 10 Years of Incorporation",
      "Enhanced Cash Flow for Business Expansion",
      "Recognition as an Innovative Startup by IMB",
      "Increased Credibility with Investors and Partners",
      "Competitive Advantage in the Market",
      "Access to Government Incentives and Programs",
      "Improved Financial Planning Opportunities",
      "Capital Conservation for Growth and Scaling",
      "Stronger Valuation Metrics for Future Funding"
    ],
    requirements: [
      "DPIIT Recognition Certificate",
      "Company Registration Certificate",
      "PAN Card of the Company",
      "GST Registration Certificate",
      "Directors' KYC Documents (PAN, Aadhaar)",
      "Detailed Business Plan",
      "Innovation Description Document",
      "Audited Financial Statements",
      "Annual Tax Returns for Previous Years",
      "Projected Financial Statements",
      "Details of Intellectual Property (if any)",
      "Information on External Funding (if any)",
      "Details of Patents/Trademarks Filed",
      "Self-Declaration in Prescribed Format"
    ],
    process: [
      {
        title: "Eligibility Assessment",
        description: "We conduct a thorough analysis to determine if your startup meets the eligibility criteria for 80 IAC exemption."
      },
      {
        title: "DPIIT Registration Verification",
        description: "We verify your DPIIT recognition status and assist with registration if not already completed."
      },
      {
        title: "Documentation Collection",
        description: "Our team helps gather all required documents for the Inter-Ministerial Board (IMB) application."
      },
      {
        title: "Business Plan Development",
        description: "We assist in creating a comprehensive business plan highlighting your startup's innovation and potential."
      },
      {
        title: "IMB Application Preparation",
        description: "We prepare your application for the Inter-Ministerial Board with supporting documents and evidence of innovation."
      },
      {
        title: "Application Submission",
        description: "We submit your application through the official Startup India portal."
      },
      {
        title: "Representation Assistance",
        description: "If required, we help prepare for and provide representation during the IMB review process."
      },
      {
        title: "Certificate Procurement",
        description: "Upon approval, we help you obtain the 80 IAC tax exemption certificate from tax authorities."
      }
    ],
    faqs: [
      {
        question: "What is 80 IAC tax exemption?",
        answer: "Section 80 IAC of the Income Tax Act provides eligible startups with a 100% tax deduction on profits for any 3 consecutive years out of the first 10 years of operation. This exemption is specifically designed to support innovative startups recognized by the Inter-Ministerial Board (IMB)."
      },
      {
        question: "What are the eligibility criteria for 80 IAC tax exemption?",
        answer: "To be eligible, a startup must: (1) be incorporated as a private limited company, LLP, or partnership firm; (2) be registered with DPIIT; (3) have been incorporated on or after April 1, 2016; (4) have a total turnover not exceeding ₹100 crores since incorporation; (5) be working towards innovation, development, or improvement of products/processes/services with potential for commercial creation of wealth; and (6) be approved by the Inter-Ministerial Board (IMB)."
      },
      {
        question: "How is 80 IAC exemption different from Angel Tax exemption?",
        answer: "While Angel Tax exemption (Section 56(2)(viib)) provides relief from tax on investments received above fair market value, 80 IAC provides a 100% deduction on profits for 3 consecutive years. Angel Tax exemption focuses on capital received, while 80 IAC focuses on profits generated by the startup. A startup can avail both exemptions if eligible."
      },
      {
        question: "How long does it take to get 80 IAC approval?",
        answer: "The process typically takes 2-3 months from application to approval, including the IMB review. However, the timeline can vary based on the volume of applications, the complexity of your innovation assessment, and any additional information requests from the board."
      },
      {
        question: "Can all DPIIT recognized startups get 80 IAC exemption?",
        answer: "No, DPIIT recognition is necessary but not sufficient for 80 IAC exemption. The startup must additionally be approved by the Inter-Ministerial Board (IMB), which evaluates the innovation, scalability, and potential impact of the business model. Only startups that demonstrate genuine innovation in products, processes, or services are approved for this exemption."
      }
    ]
  };

  return <ServiceDetail {...serviceData} />;
};

export default TaxExemption80IAC;
