// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yhwpuozoljtljerqwqao.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlod3B1b3pvbGp0bGplcnF3cWFvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEyNTQ3MTYsImV4cCI6MjA1NjgzMDcxNn0.8QEAPF0VoQ1QTUhDMrl_Dph-FNcqWGuAdvoqAfkXK3U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);